language: python
python:
  - "3.8"

install:
  - pip install -r requirements.txt

script:
  - pylint --disable=C0114,C0116,C0115,W0611 department_app
  - coverage run --source=department_app -m pytest department_app/tests
  - coverage report

after_success:
  - coveralls